name: todo_sync_app
description: Offline + Online To-Do app (SQLite + Firebase) with sync.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Local storage (SQLite)
  sqflite: ^2.3.3
  path: ^1.9.0

  # Firebase
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0

  # Utilities
  connectivity_plus: ^6.0.5
  uuid: ^4.5.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
